name: i2dl
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - intel-openmp=2023.1.0
  - joblib=1.5.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.4
  - numexpr=2.11.0
  - numpy-base=2.3.1
  - openssl=3.0.17
  - pip=25.1
  - python=3.11.11
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - readline=8.2
  - scikit-learn=1.7.1
  - scipy=1.16.0
  - setuptools=72.1.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.0
      - asttokens==2.4.1
      - backcall==0.2.0
      - backports-functools-lru-cache==1.6.4
      - cachetools==5.5.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - executing==2.0.1
      - filelock==3.13.1
      - fonttools==4.50.0
      - fsspec==2024.6.1
      - google-auth==2.40.3
      - google-auth-oauthlib==0.4.6
      - grpcio==1.72.1
      - hf-xet==1.1.3
      - huggingface-hub==0.32.5
      - idna==3.10
      - importlib-metadata==6.3.0
      - ipykernel==6.29.4
      - ipython==8.23.0
      - ipywidgets==8.1.7
      - jedi==0.19.1
      - jinja2==3.1.4
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.5
      - markdown==3.8
      - markupsafe==2.1.5
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.6
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - packaging==24.0
      - pandas==2.2.1
      - parso==0.8.3
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.3.0
      - platformdirs==4.2.0
      - prompt-toolkit==3.0.43
      - protobuf==3.19.6
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pygments==2.17.2
      - pyparsing==3.1.2
      - pytz==2024.1
      - pyyaml==6.0.2
      - pyzmq==25.1.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - ruamel-yaml==0.18.15
      - ruamel-yaml-clib==0.2.12
      - safetensors==0.5.3
      - seaborn==0.13.2
      - six==1.16.0
      - stack-data==0.6.3
      - sympy==1.13.3
      - tensorboard==2.9.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tokenizer==3.4.5
      - tokenizers==0.21.1
      - torch==2.2.2+cu121
      - torchaudio==2.2.2+cu121
      - torchvision==0.17.2+cu121
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.2
      - transformers==4.52.4
      - triton==2.2.0
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - urllib3==2.4.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - zipp==3.15.0
prefix: /home/jamesye/anaconda3/envs/i2dl
